name: Android CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Unit Tests
        run: ./gradlew test

  build:
    needs: [unit_tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v3
        run: sdkmanager tools platform-tools
        with:
          accept-android-sdk-licenses: Yes

      - name: Clean the build
        run: ./gradlew clean

      - name: Generate Release APK
        run: ./gradlew assembleRelease

      - name: Sign app APK
        uses: r0adkll/sign-android-release@v1
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ALIAS_KEY_PASSWORD }}
      - uses: actions/upload-artifact@main
        with:
          name: release.apk
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
      - uses: actions/upload-artifact@main
        with:
          name: mapping.txt
          path: app/build/outputs/mapping/release/mapping.txt



